name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }} 
          projectKey: "stphnsmpsn.github.io"
          projectName: "stphnsmpsn.github.io"
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Node Modules
        run: npm install

      - name: Deploy GitHub Page
        run: npm run deploy
    
        
