
name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: SonarQube Scan
        run: ./sonar.sh ${{ secrets.SONARQUBE_HOST }} ${{ secrets.SONARQUBE_TOKEN }} 
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Node Modules
        run: npm install

      - name: Deploy GitHub Page
        run: npm run deploy
