
name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Modules
        run: npm install
      - name: SonarQube Scan
        run: ./sonar.sh ${{ secrets.SONARQUBE_HOST }} ${{ secrets.SONARQUBE_TOKEN }} 
      - name: Deploy GitHub Page
        run: npm run deploy
